// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD80_ThL77B7f4WAzowA3KnDgGQX7N2akI',
    appId: '1:418152706925:web:75f0af440d935451e22064',
    messagingSenderId: '418152706925',
    projectId: 'oyunlab-sistem',
    authDomain: 'oyunlab-sistem.firebaseapp.com',
    storageBucket: 'oyunlab-sistem.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbWPxWSacRIXn5MKLuCdk7N6mhj-hTp9w',
    appId: '1:418152706925:android:0877af6aa869cfa1e22064',
    messagingSenderId: '418152706925',
    projectId: 'oyunlab-sistem',
    storageBucket: 'oyunlab-sistem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjsSeSTz8VW6_-Ft_nL6fuma9sVXM4Zy4',
    appId: '1:418152706925:ios:510e2caaea812a05e22064',
    messagingSenderId: '418152706925',
    projectId: 'oyunlab-sistem',
    storageBucket: 'oyunlab-sistem.firebasestorage.app',
    iosBundleId: 'com.example.oyunlab',
  );
}
